### ISSUE TITLE
Results of fractionalAirlineDecomposition  with (log=true)

### ISSUE THREAD

**Issue by ChristianeHofer** [rjdemetra/rjd3highfreq#20]
I think there is something wrong with  fractionalAirlineDecomposition  with (log=true)
My example in R: 

set.seed(2358)
all <- tssim::sim_daily(N=5)
series <- all$original
y_time <- zoo::index(series)
a_result <- rjd3highfreq::fractionalAirlineDecomposition(series, 7, log = TRUE, y_time = y_time)

a_result
a_result$decomposition$s[1817:1827]
a_result$decomposition$y[1817:1827]
all$original[1817:1827]

The seasonal component s in a_result is different from a_result$decomposition$s. The same with the orginal y in a_result and a_result$decomposition$y. 

I think there is a problem in [https://github.com/rjdemetra/rjd3highfreq/blob/ffe5d14682c1bee95e7d6715ca9e9a1745e7b9d6/R/jd3_fractionalairline.R#L37](url) that in line 43 the decomposition is done for y also for log=T and not for ln(y). (Line 77 looks similar. )

**Comment by palatej** [comment]
Hi Christiane, 
In the case of a log transformation, a_result$decomposition$... provides the different components based on the series in logs.
You can see in the "print" method that those components are then simply back-transformed by means of the "exp" function. 
The "rjd3highfreq" is still in an exploratory phase. In a future version, the result should also contain a "final decomposition", with the exp(components) corrected for possible biases.
So, the current code doesn't contain actual mistakes, but it is incomplete and misleading. I will modify it.
